### ISSUE TITLE
Has this project already done?

### ISSUE THREAD

**Issue by drinktee** [andrewstucki/jobs#1]
Hi, thx for opensource this repo. I'm going to start a job queue project and I see this. Does this project being developing?

**Comment by andrewstucki** [comment]
Hi @drinktee this was originally a bit of a spike while trying to figure out some stuff around the priority queue implementation that I wrote for [faktory](https://github.com/contribsys/faktory). I really have no plans to add more features to it or work on it much, just put it out there in case anyone else wanted some ideas.
